services:
  # Base de données PostgreSQL
  postgres:
    image: postgres:17
    container_name: aicn-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aicn_db
    ports:
      - "5439:5432"
    volumes:
      # - postgres-data:/var/lib/postgresql/data
      - ./scripts/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aicn-network

  # Backend Clojure application
  backend:
    build:
      context: ./packages/backend
    container_name: aicn-backend
    environment:
      PORT: 1337
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      SSL_MODE: disable
      COOLIFY_DOMAIN: yggg488g8cos0ogwkgog0oks.185.172.57.92.sslip.io
    expose:
      - "1337"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - aicn-network

  # Frontend React application
  frontend:
    build:
      context: ./packages/frontend
    container_name: aicn-frontend
    environment:
      COOLIFY_DOMAIN: yggg488g8cos0ogwkgog0oks.185.172.57.92.sslip.io
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - aicn-network


# volumes:
  # postgres-data:

networks:
  aicn-network:
    driver: bridge
