# fly.toml app configuration file generated for aicn-app on 2025-04-17T10:41:29+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aicn-app'
primary_region = 'cdg'

[build]
  dockerfile = 'packages/backend/Dockerfile'

[env]
  PORT = '1337'
  HOST = '0.0.0.0'

[http_service]
  internal_port = 1337
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1
  processes = ['app']
  
  [[http_service.checks]]
    interval = "10s"
    timeout = "10s"
    grace_period = "60s"
    method = "get"
    path = "/api/health"
    protocol = "http"

[[services]]
  protocol = 'tcp'
  internal_port = 1337

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
